[project]
authors = ["fferraro <federico_ferraro@outlook.com>"]
channels = ["dnachun", "conda-forge", "bioconda"]
name = "MethaDory"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
r-shinydashboard = ">=0.7.2,<0.8"
r-dt = ">=0.33,<0.34"
r-ggplotify = ">=0.1.2,<0.2"
r-umap = ">=0.2.10.0,<0.3"
r-patchwork = ">=1.3.0,<2"
bioconductor-pcatools = ">=2.18.0,<3"
"r-data.table" = ">=1.17.0,<2"
r-tidyverse = ">=2.0.0,<3"
r-caret = ">=6.0_94,<7"
bioconductor-methylimp2 = ">=1.2.0,<2"
bioconductor-champdata = ">=2.38.0,<3"
bioconductor-bumphunter = ">=1.48.0,<2"
bioconductor-complexheatmap = ">=2.22.0,<3"
r-rtsne = ">=0.17,<0.18"
r-shinyfiles = ">=0.9.3,<0.10"
bioconductor-epidish = ">=2.22.0,<3"
