[workspace]
authors = ["fferraro"]
channels = ["dnachun", "conda-forge", "bioconda", "r"]
name = "MethaDory"
platforms = ["osx-64", "linux-64"]

[tasks]

# Launch Shiny GUI application
MethaDory = { cmd = "cd src/shiny && Rscript app.R" }

# Command-line analysis tools
MethaDory_cli = { cmd = "cd src/cli && Rscript run_methadory.R" }
MethaDory_html = { cmd = "cd src/cli && Rscript generate_methadory_html_report.R" }

MethaDory_ont_extract_cmd = { cmd = "cd ONT-Input-preparation && bash MethaDory-extract-methylation.sh" }
MethaDory_ont_extract = { cmd = "pixi run -e modkit MethaDory_ont_extract_cmd" }
MethaDory_ont_input   = { cmd = "pixi run -e modkit MethaDory_ont_input" }


[dependencies]
bioconductor-genomeinfodb = ">=1.42.0,<2"
bioconductor-watermelon = ">=2.12.0,<3"
bioconductor-methylumi = ">=2.52.0,<3"
bioconductor-methylimp2 = ">=1.2.0,<2"
bioconductor-bumphunter = ">=1.48.0,<2"
bioconductor-complexheatmap = ">=2.22.0,<3"
bioconductor-epidish = ">=2.22.0,<3"
bioconductor-pcatools = ">=2.18.0,<3"
bioconductor-champdata = ">=2.38.0,<3"
bioconductor-biocparallel = ">=1.40.0,<2"

r-shiny = ">=1.8.0,<2"
r-shinydashboard = ">=0.7.2,<0.8"
r-shinyfiles = ">=0.9.3,<0.10"
r-shinyjs = ">=2.1.0,<3"
r-shinybusy = ">=0.3.3,<0.4"
r-dt = ">=0.33,<0.34"

r-tidyverse = ">=2.0.0,<3"
"r-data.table" = ">=1.17.0,<2"
r-caret = ">=6.0_94,<7"
r-kernlab = ">=0.9_33,<0.10"
r-butcher = ">=0.3.6,<0.4"

r-ggplotify = ">=0.1.2,<0.2"
r-patchwork = ">=1.3.0,<2"
r-plotly = ">=4.10.4,<5"
r-scales = ">=1.3.0,<2"
r-ggrepel = ">=0.9.6,<0.10"
r-gridextra = ">=2.3,<3"

r-openxlsx = ">=4.2.8,<5"
r-markdown = ">=1.13,<2"
r-jsonlite = ">=1.8.8,<2"
r-base64enc = ">=0.1_3,<0.2"
r-htmlwidgets = ">=1.6.4,<2"

r-fs = ">=1.6.4,<2"
r-biocmanager = ">=1.30.25,<2"
r-circlize = ">=0.4.16,<0.5"