[workspace]
channels = ["conda-forge", "bioconda"]
name = "MetaDory-Extract-ONT"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ont-modkit = ">=0.4.4,<0.5"
bedtools = ">=2.31.1,<3"
r-base = ">=4.4.3,<4.5"
r-tidyverse = ">=2.0.0,<3"
r-purrr = ">=1.0.4,<2"
